from_latest_tag = true
ignore_merge_commits = true
tag_prefix = "v"
branch_whitelist = ["main"]
pre_bump_hooks = ["python3 scripts/set-version.py {{version}}"]

[commit_types]
build = { omit_from_changelog = true }
chore = { omit_from_changelog = true }
ci = { omit_from_changelog = true }
docs = { omit_from_changelog = true }
feat = { changelog_title = "Added" }
fix = { changelog_title = "Fixed" }
perf = { changelog_title = "Performance" }
refactor = { changelog_title = "Changed" }
release = { omit_from_changelog = true }
style = { omit_from_changelog = true }
test = { omit_from_changelog = true }

[changelog]
path = "CHANGELOG.md"
template = ".config/cog-changelog.tera"
